### ISSUE TITLE
taking long time to get response every 3 sec

### ISSUE THREAD

**Issue by selvam920** [microsoft/dev-tunnels#276] opened 2023-07-13 03:49 UTC
when access the api every 2 or 3 sec once unable to get the response and did not throw any error response.

and also i checked in dev tools, there is no hit for that api

**Comment by selvam920** [comment] 2023-07-13 03:50
Tunnel CLI version: 1.0.734+7dea58c935

Tunnel service URI        : https://global.rel.tunnels.api.visualstudio.com/
Tunnel service version    : 1.0.735.38760 (68979c252c; 2023-07-08 01:29:56Z)
Tunnel service cluster    : asse

**Comment by selvam920** [comment] 2023-07-13 03:50
due to this unable to use devtunnel

**Comment by derekbekoe** [comment] 2023-07-13 16:42
Can you share with us the tunnel id or url?

**Comment by selvam920** [comment] 2023-07-13 16:44
z5vs7f5r.asse

**Comment by selvam920** [comment] 2023-07-13 16:53
now also tried, same issue happening

**Comment by selvam920** [comment] 2023-07-13 17:07
after request id 7e7416cc-37b0-4f0a-b6fc-bfcf8f82466d i did not get response from http call, only loading did not get response

**Comment by selvam920** [comment] 2023-07-13 17:08
No entry in the DevTools inspect page

**Comment by selvam920** [comment] 2023-07-13 17:10
after timeout
<html>
<head><title>504 Gateway Time-out</title></head>
<body>
<center><h1>504 Gateway Time-out</h1></center>
<hr><center>nginx</center>
</body>
</html>

**Comment by selvam920** [comment] 2023-07-13 17:14
request same api 4 or 7 times it get timeout

**Comment by selvam920** [comment] 2023-07-13 17:19
i used asp.net core kestral web server
Host.CreateDefaultBuilder(args)
                       
                .ConfigureWebHostDefaults(webBuilder =>
                {
                    webBuilder
                     .UseUrls("http://*:3333")
                     .UseKestrel()
                     .UseContentRoot(Directory.GetCurrentDirectory())
                     .UseIISIntegration()
                     .UseStartup<Startup>();
                });

**Comment by selvam920** [comment] 2023-07-13 17:37
<img width="817" alt="image" src="https://github.com/microsoft/dev-tunnels/assets/20491308/d19d692d-79dc-4e9b-afc1-9ffa3150e3c6">

**Comment by selvam920** [comment] 2023-07-13 17:37
i did not get request id after timeout in the exception

**Comment by derekbekoe** [comment] 2023-07-13 20:42
We're taking a look. Thanks.

**Comment by selvam920** [comment] 2023-07-14 02:27
when can i expect this fix?

**Comment by selvam920** [comment] 2023-07-15 03:05
@derekbekoe updated to Tunnel CLI version: 1.0.754+e72f0b94ac
still this issue exist

**Comment by jasongin** [comment] 2023-07-17 18:58
@selvam920 Please try it again now.

**Comment by derekbekoe** [comment] 2023-07-28 18:24
Closing this as we believe the issue is resolved. If you're still seeing issues here, feel free to comment.

**Closed by derekbekoe** 2023-07-28 18:24 UTC
Labels: bug
