### ISSUE TITLE
Why does dev-tunnels lower the header names ?

### ISSUE THREAD

**Issue by alefcarlos** [microsoft/dev-tunnels#406] opened 2024-02-28 03:12 UTC
While I was debbuing an application that calculate hash using the header name I discovered that dev-tunnels lowers the header name, an `curl` example:

```
curl --location 'https://host.devtunnels.ms/v1/actions/azdo-build-validation:add' \
--header 'X-OpsLevel-Timing: 1709083272' \
--header 'X-OpsLevel-Signature: sha256=347df57a124347c6db9c4117401763d4e6df61396623faf8c5c8a14f5c3984bd' \
--header 'Content-Type: application/json' \
--data '{
  "service": "pla-opslevel-integration-api",
  "repository": "hidrovias/pla-sln-opslevel-integration"
}'
```

And the log output using HttpLogginMiddleware(ASPNET CORE):

```
info: Microsoft.AspNetCore.HttpLogging.HttpLoggingMiddleware[9]
      Request and Response:
      Protocol: HTTP/2
      Method: POST
      Scheme: https
      PathBase:
      Path: /v1/actions/azdo-build-validation:add
      Accept: */*
      Host: localhost:5011
      User-Agent: Faraday v1.10.3
      Accept-Encoding: gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      baggage: [Redacted]
      Content-Type: application/json
      traceparent: [Redacted]
      tracestate: [Redacted]
      Content-Length: 105
      x-request-id: [Redacted]
      x-real-ip: [Redacted]
      x-forwarded-proto: [Redacted]
      x-forwarded-host: [Redacted]
      x-forwarded-port: [Redacted]
      x-forwarded-scheme: [Redacted]
      x-original-uri: [Redacted]
      x-scheme: [Redacted]
      x-opslevel-timing: 1709085444
      x-opslevel-signature: sha256=32c77d5c0ee8bc84dcfae71838c5c7eb1fe17a8f3d3c5d6307d072460ba4c614
      x-datadog-trace-id: [Redacted]
      x-datadog-parent-id: [Redacted]
      x-datadog-sampling-priority: [Redacted]
      x-datadog-tags: [Redacted]
      sentry-trace: [Redacted]
      x-original-proto: [Redacted]
      x-forwarded-for: [Redacted]
      StatusCode: 401
      Content-Type: text/plain
      RequestBody: {
  "service": "pla-opslevel-integration-api",
  "repository": "hidrovias/pla-sln-opslevel-integration"
}
      RequestBodyStatus: [Completed]
      Duration: 59592,9107
```

using the configuration:

```csharp
        builder.Services.AddHttpLogging(logging =>
        {
            logging.LoggingFields = HttpLoggingFields.RequestPropertiesAndHeaders | HttpLoggingFields.ResponsePropertiesAndHeaders | HttpLoggingFields.RequestBody | HttpLoggingFields.Duration;
            logging.RequestHeaders.Add("X-OpsLevel-Signature");
            logging.RequestHeaders.Add("X-OpsLevel-Timing");
        });
```

Is this the expected behaviour ?

**Comment by derekbekoe** [comment] 2024-03-01 20:54
HTTP header names are case-insensitive [1][2]. Also, in some cases, they must actually be lowercase.

[1] https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers
[2] https://www.rfc-editor.org/rfc/rfc7230#section-3.2
[3] https://www.rfc-editor.org/rfc/rfc7540#section-8.1.2

**Comment by 1bberto** [comment] 2024-03-02 01:11
In theory it should not mutate the request, for example ngrok does not change the request headers 👀

**Comment by derekbekoe** [comment] 2024-03-04 20:28
Thanks for the feedback.
We'll take a look to see if we can be more consistent and use the provided casing here!

**Comment by IlyaBiryukov** [comment] 2024-03-28 01:09
If you want to keep headers case, please ensure that your client does not use HTTP/2 protocol and use the regional tunnel endpoint.

Lowering header case is exactly the expected behavior when request is sent using HTTP/2, as per RFC 7540 [states](https://www.rfc-editor.org/rfc/rfc7540#section-8.1.2):
> Just as in HTTP/1.x, header field names are strings of ASCII characters that are compared in a case-insensitive fashion. However, header field names MUST be converted to lowercase prior to their encoding in HTTP/2. A request or response containing uppercase header field names MUST be treated as malformed.

Your headers will be converting to lowercase even if you use HTTP1.1 if your tunnel resides in a different region from where it is served, and you don't use a region-specific tunnel host name (like it is above with "usw2" region subdomain).  When forwarded HTTP tunnel traffic goes between the serving region and the tunnel home region, if those regions are different, we use HTTP/2 to improve performance. 

In your example above I see that you use the global tunnel endpoint, `{tunnel}.devtunnels.ms`. It is not region specific, so this cross-region traffic may be the reason if you use HTTP1.1.

@alefcarlos Is using a region-specific tunnel endpoint an option for you?

I've verified that devtunnels service respects the headers case if requests are sent with HTTP 1.1 to the tunnel home region endpoint and converts the headers to lower case with HTTP/2.

``` bash
# Run http://locahost:9080 that echoes back the headers. May be another port for you. Runs in a dedicated shell.
devtunnel echo

# Host the echo tunnel. You need to be logged in. If you run an authenticated tunnel without -a, you'll need to pass the auth header with curl.
devtunnel host -p 9080 -a

# Connect to the tunnel's home region with HTTP 1.1 and see the header case is not changed
curl --location "https://{your_tunnel_name}-9080.usw2.devtunnels.ms" --http1.1 --header 'X-OpsLevel-Timing: bar'
...
X-OpsLevel-Timing: bar
...

# Connect to the tunnel with HTTP/2 and see the header converted to lower case
curl --location "https://{your_tunnel_name}-9080.usw2.devtunnels.ms" --http2 --header 'X-OpsLevel-Timing: bar'
...
x-opslevel-timing: bar
...

# Connect to the tunnel with HTTP 1.1 from different region and see the header converted to lower case
# The same happens if region-agnostic endpoint, {your_tunnel_name}-9080.devtunnels.ms is used and traffic manager picks up a different region.
curl --location "https://{your_tunnel_name}-9080.usw3.devtunnels.ms" --http1.1 --header 'X-OpsLevel-Timing: bar'
...
x-opslevel-timing: bar
...
```

**Comment by derekbekoe** [comment] 2024-04-22 20:04
Closing as we've provided a detailed response above with details.

**Closed by derekbekoe** 2024-04-22 20:04 UTC
