### ISSUE TITLE
Docs: Link to ToS is encrypted with AADIP, non-MSFT users cannot read it

### ISSUE THREAD

**Issue by sean-r-williams** [microsoft/dev-tunnels#484] opened 2024-09-26 23:52 UTC
Hey folks,

I was looking through the dev-tunnels documentation and noticed the FAQ ([section "What are the license terms for dev tunnels?"](https://learn.microsoft.com/en-us/azure/developer/dev-tunnels/faq#what-are-the-license-terms-for-dev-tunnels)) links to https://aka.ms/devtunnels/tos. 

When I browse to this link, I'm served a EULA PDF that's got AAD Information Protection enabled. It looks like users outside Microsoft's AAD tenant are unable to decrypt this document.

The document itself is hosted [in MicrosoftDocs/azure-dev-docs](https://github.com/MicrosoftDocs/azure-dev-docs/blob/main/articles/dev-tunnels/faq.md), but issues aren't accepted there. @justingrote filed microsoftdocs/azure-dev-docs#1409 in an attempt to raise awareness.

Can someone from the Dev Tunnels team replace this document with an unencrypted version? (Putting the EULA on GitHub alongside other docs might be a good solution as well.)

**Comment by derekbekoe** [comment] 2024-09-27 18:19
Thanks for raising this. Closing as a duplicate of https://github.com/microsoft/dev-tunnels/issues/483 so we can track there.

**Closed by derekbekoe** 2024-09-27 18:19 UTC
