### ISSUE TITLE
Getting HTTP 429 on dev tunnel - Why?

### ISSUE THREAD

**Issue by clement911** [microsoft/dev-tunnels#491] opened 2024-10-16 00:35 UTC
Hi there,

We've just started using dev tunnel to receive webhooks on local dev environments.
This worked for a few minutes and we've already start HTTP 429 Too many requests errors.

We don't understand why.
As far as we can gather, we haven't gone over any limits yet. We've literally just started playing with it.

Unfortunately the HTTP response from the tunnel give any message about what limit we have supposedly breached.
Can someone shed some light on the matter?

Here is a screenshot from the HTTP headers returned:
![Image](https://github.com/user-attachments/assets/5751c139-75c7-49c8-97b7-aacf9a4cc45f)

**Comment by fogatond** [comment] 2024-10-16 07:47
We are experiencing same issue for like 3 days now. We used dev tunnel for half a year without issue but it stopped working now.

**Comment by jkrejcar** [comment] 2024-10-16 07:47
I’m encountering the same issue with dev tunnel—everything works for a few minutes, and then I start getting HTTP 429 “Too many requests” errors. Similar to your experience, I haven’t exceeded any apparent limits, it’s quite frustrating...

**Comment by jkrejcar** [comment] 2024-10-16 07:59
![Image](https://github.com/user-attachments/assets/b43abdac-54f5-4194-a8fd-2846beddf1a8)

**Comment by faire2** [comment] 2024-10-16 07:59
I have encountered the same problem. We have been using devtunnels for some time, but to my knowledge we have not encountered this problem until recently. Currently we are encountering this issue to such an extent that it is blocking our work. `BandwidthPerUser` is under 10%.

**Comment by alexvobo** [comment] 2024-10-16 22:51
We have also been experiencing this issue. Using 1 tunnel, 2 ports (front end/server).

For us the trigger is Next.js hot reloading. We switched from VS Code dev tunnels to dev tunnel cli and that fixed it for a day now it's back to kicking us off every time we hit save and trigger a hot reload.

**Comment by gkDoSt** [comment] 2024-10-17 12:09
i am facing the same issue with our .NET 8 / VITE / REACT setup

**Comment by MichaMican** [comment] 2024-10-17 12:09
We have the exact same issue when using .NET with vite + React

**Comment by MooseCoding** [comment] 2024-10-17 12:17
I'm also having this issue with Next.js

**Comment by russgove** [comment] 2024-10-17 20:02
back to ngrok :-)

**Comment by IlyaBiryukov** [comment] 2024-10-17 21:57
We're going to increase `ClientConnectionsPerPort` connection limit. The change should deploy pretty quickly. Sorry for the inconvenience.

The response headers were not correct for these 429s - the limitation that caused 429 was this `ClientConnectionsPerPort: max 20`, not the `HttpRequestRatePerPort`. The fix for the response headers will come out later on.

**Comment by clement911** [comment] 2024-10-17 22:47
It would be great if you could also include a human friendly message indicating the limit that was breached (the headers are good but I haven't seem them documented anywhere).

**Comment by shanematte** [comment] 2024-10-18 05:06
I've been having this problem too. Any news when it will be fixed?

**Comment by faire2** [comment] 2024-10-18 06:14
> We're going to increase `ClientConnectionsPerPort` connection limit. The change should deploy pretty quickly. Sorry for the inconvenience.
> 
> The response headers were not correct for these 429s - the limitation that caused 429 was this `ClientConnectionsPerPort: max 20`, not the `HttpRequestRatePerPort`. The fix for the response headers will come out later on.

Has the change rolled out? We're still running into the same problem.

**Comment by MichaMican** [comment] 2024-10-18 07:25
@IlyaBiryukov 
> We're going to increase `ClientConnectionsPerPort` connection limit. The change should deploy pretty quickly. Sorry for the inconvenience.
> 
> The response headers were not correct for these 429s - the limitation that caused 429 was this `ClientConnectionsPerPort: max 20`, not the `HttpRequestRatePerPort`. The fix for the response headers will come out later on.

What is the new limit? For Vite it is common and by design to serve hundrets of files on initial load (see [this issue](https://github.com/vitejs/vite/issues/13542#issuecomment-1597314562) on vite side). As this is the "modern approach", one could even say industry standard (and even bundled with the VS Templates - it would be crutial to support this "Basic usecase"

___

@clement911
> Are DevTunnels generally stable or is this a common occurrence? I have been using ngrok for 7 years and never had an issue. I have used dev tunnels for 5 minutes and already ran into this issue. I am hoping to move our team off ngrok and on dev tunnels. I'm trying to get a sense of whether dev tunnel is reliable enough to make the switch.

We switched from ngrok quite some time ago - Our project still had the old static file serve model therefor we never encountered throtteling issues so far. After migrating to vite this started to become an issue.
But to be fair they stated in there documentation from the get go
> To request higher usage limits for dev tunnels, open an issue in our [GitHub repo](https://github.com/Microsoft/dev-tunnels/issues). In the issue, include which limit you'd like increased and why.

([Source](https://github.com/MicrosoftDocs/azure-docs/blob/main/includes/dev-tunnels/dev-tunnels-service-limits.md))

So that's basically what OG did in this thread ;)

**Comment by IlyaBiryukov** [comment] 2024-10-18 16:24
The change to the limits is rolled out. The new limit is 200 connections per tunnel port.

**Comment by pjninnim** [comment] 2024-10-21 07:28
I'm still seeing `ClientConnectionsPerPort: max 20` not `ClientConnectionsPerPort: max 200`? Is there anything I need to do to see this change so the 429 error can be resolved? Thanks

**Comment by gkDoSt** [comment] 2024-10-21 07:30
The limit still seems to be at 20 requests for me and i get a 429 for my requests.

![Image](https://github.com/user-attachments/assets/2a30753f-9e15-475c-8847-f2d4db75acdb)

**Comment by StefanH114** [comment] 2024-10-21 10:13
I have the same issue with my  .NET with vite + React App.

**Comment by andresito1969** [comment] 2024-10-21 10:40
Same problem, working only for few seconds until i try to request to somewhere, then all crashes showing 429 HTTP error.

Only working with 2 connections and 1 port...

Happening since 16th oct 2024 at least....

**Comment by fogatond** [comment] 2024-10-21 13:10
Our solution needs like 600 connections because is it split into 3 components that runs on different URLs at the same time. Imagine like client operator and one shared component. So to use it, we need to have at least 600 connection for a short period of time. To be totally safe, 1k is optimal, is this possible?

**Comment by IlyaBiryukov** [comment] 2024-10-22 22:29
@fogatond we're going to change the limit to 1k.

@andresito1969, @StefanH114 If the issue still reproduces for you, can you please share your tunnel port URLs and time when you hit it? Then I can check the tunnels telemetry. You can reach me at my first name dot my last name at Microsoft dot com. I double checked and I see the new limits are in effect now, `ClientConnectionsPerPort: max 200` is returned on 429s.

@faire2 re as to why the limit is enforced, there was an outage some time ago when some cross-regional tunnel kept open tens of thousands of connections to a forwarded port. This caused socket exhaustion and brief service outage in one region, so we had to limit the number of connections opened when clients connect to forwarded ports. We already impose 20 connections limit per tunnel that is applied to SDK client connections.

**Comment by faire2** [comment] 2024-10-23 06:13
Thanks for the explanation, I appreciate it. We're really looking forward for the new limit, working with devtunnels was awesome and I would love to be able to use it again.

**Comment by pjninnim** [comment] 2024-10-23 07:27
@IlyaBiryukov I just tried this out and I cannot see the increase so I've still got the same issue, please see below:
![Image](https://github.com/user-attachments/assets/738daf68-e544-4a05-aa36-11f59f6ce4a3)

**Comment by UKeyboard** [comment] 2024-10-23 10:24
The issue still reproduces for me.

![Image](https://github.com/user-attachments/assets/e1cf9b9c-3220-481f-bb4b-fe3aa1df35d4)

**Comment by conradmoyidv** [comment] 2024-10-23 12:37
I'm experiencing this too - It usually happens around 15 minutes into hosting locally 

![Image](https://github.com/user-attachments/assets/5b5de340-7ead-4179-9b6b-e3cbda55f6d1)

**Comment by andresito1969** [comment] 2024-10-23 12:43
Still hapenning and i sent an email to you this morning (CET Madrid time zone) @IlyaBiryukov 

Since it's not working i'm using github pages, but obviously is way too slow to do that, unluckily i have to work with gh pages until it's fixed, if you need more info we talk via mail, have a great day.

**Comment by alexvobo** [comment] 2024-10-23 15:38
> I'm experiencing this too - It usually happens around 15 minutes into hosting locally
> 
> ![Image](https://github.com/user-attachments/assets/5b5de340-7ead-4179-9b6b-e3cbda55f6d1)

Same. Recent changes made it a bit better than before, but it's still unusable. Hot reload hits rate limit way too quickly.

**Comment by conradmoyidv** [comment] 2024-10-23 16:58
> > I'm experiencing this too - It usually happens around 15 minutes into hosting locally
> > ![Image](https://github.com/user-attachments/assets/5b5de340-7ead-4179-9b6b-e3cbda55f6d1)
> 
> Same. Recent changes made it a bit better than before, but it's still unusable. Hot reload hits rate limit way too quickly.

I've found a temporary fix since you mentioned hot reload which is working fine for me so far. I'm using VS Code Live Server extension and turns out dev tunnels doesn't like it saving and refreshing the page too often which is understandable.

 **I added `"liveServer.settings.ignoreFiles":["**"]` to my User/settings.json** which stops the live refreshing so I'm only refreshing the page when I need to with ctrl shift r. 

Hope this helps

**Comment by IlyaBiryukov** [comment] 2024-10-23 18:01
I could find these in our telemetry. We're investigating why the policy change didn't apply to some regions. It did apply to West US 2 & West US 3 regions though.

**Comment by IlyaBiryukov** [comment] 2024-10-23 21:40
The policy change to 200 max connections per tunnel port should be applied everywhere by now. What happened is that after we updated policy's config map in our clusters, we assumed the service pods had picked up the changes. We verified that the new policy was in effect in US West region and that was the case. Well, it happened that an automatic cluster update did run right after policy update in US West and restarted our service pods, which made them reload the policy. In other regions we just checked the config map. As the other regions didn't run automatic cluster update and the pods didn't pick up the change, the old policy stayed in effect. So, restarting the pods now applied the updated policy.

Re further upping the limit to 1K, we'll have to delay that a bit. There is deployment freeze in our division now, only critical fixes can make it. We can get to it after November the 7th.

**Comment by pjninnim** [comment] 2024-10-24 06:13
@IlyaBiryukov I can confirm this has now resolved my issue due to the fact that the `ClientConnectionsPerPort: max 20` has now been removed:
![Image](https://github.com/user-attachments/assets/0aa5922a-2608-4de7-9296-b17767fa986f)
Thanks!

**Comment by fogatond** [comment] 2024-10-24 07:36
> The policy change to 200 max connections per tunnel port should be applied everywhere by now. What happened is that after we updated policy's config map in our clusters, we assumed the service pods had picked up the changes. We verified that the new policy was in effect in US West region and that was the case. Well, it happened that an automatic cluster update did run right after policy update in US West and restarted our service pods, which made them reload the policy. In other regions we just checked the config map. As the other regions didn't run automatic cluster update and the pods didn't pick up the change, the old policy stayed in effect. So, restarting the pods now applied the updated policy.
> 
> Re further upping the limit to 1K, we'll have to delay that a bit. There is deployment freeze in our division now, only critical fixes can make it. We can get to it after November the 7th.

Thanks Ilya, it works much better now. Will you leave ticket open until you up limit to 1k and then let us know?

**Comment by fogatond** [comment] 2024-10-25 10:25
@IlyaBiryukov Hi, my dev tunnel seems to be stuck with 199 client connections now. I stopped devtunnel host command, removed anonymous access, waited for one hour and it is still at 199. Is there any way to "disconnect" all clients? I haven't found any command in devtunnel documentation. Is this something that is relevant to this ticket? IMHO this might be culprit of why you had thousands of opened connections as mentioned below. 

> [@faire2](https://github.com/faire2) re as to why the limit is enforced, there was an outage some time ago when some cross-regional tunnel kept open tens of thousands of connections to a forwarded port. This caused socket exhaustion and brief service outage in one region, so we had to limit the number of connections opened when clients connect to forwarded ports. We already impose 20 connections limit per tunnel that is applied to SDK client connections.



Tunnel ID: chat-widget-new.euw
Port Number : 3030
Protocol : auto
Access control: {}
Client connections: 199

**Comment by IlyaBiryukov** [comment] 2024-10-25 17:02
@fogatond I'll investigate. Thanks for reporting this!

**Comment by Hewsman** [comment] 2024-10-30 10:57
![Image](https://github.com/user-attachments/assets/c1161717-991c-4f8b-b452-3b00cebfff54)
Waiting for Nov 7th. Im also experiencing this :D

**Comment by IlyaBiryukov** [comment] 2024-11-07 20:11
Deployment freeze is extended till the next Monday, 11/10. The good news is that I believe I found the root cause of issue that @fogatond reported. The next release will have both 1K limit and the fix for that issue.

**Comment by pk-nexigroup** [comment] 2024-11-13 10:06
Do you have any estimates when the fix will be released? Thank you.

**Comment by IlyaBiryukov** [comment] 2024-11-14 21:13
Release complete.

**Closed** 2024-11-15 23:24 UTC
